# title = "A CTGUer's Hugo Static Site" # 网站主标题
baseURL = 'https://crack-dawn.github.io/CTGU-Hugo-Blog.io'# 网站根目录
languageCode = 'en-us'

defaultContentLanguage = "zh-cn" # 默认语言
theme = ["FixIt","hugo-embed-pdf-shortcode"]


# 是否开启短代码
enableInlineShortcodes = true

# 是否开启评论功能
enableComments = true

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true

# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true

# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# the editor to use when creating new content
# 创建新内容时使用的编辑器
newContentEditor = "code"

## development environment compile&build
# hugo serve -D
## production environment compile&build
# hugo serve -D -e production  --gc
