# [ibruce]
#     enable = true
#     enablePost = true

[gitInfo]
    repo = "https://github.com/crack-dawn/CTGU-Hugo-Blog.io"
    branch = "master"
    dir = "content"
    issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"

[backToTop]
    enable = true
    scrollpercent = true

[readingProgress] # 全局页面 阅读进度条配置
    enable = true
    start = "left"      # 可用值：["left", "right"]
    position = "bottom"    # 可用值：["top", "bottom"]
    reversed = true
    light = ""
    dark = ""
    height = "2px"
    
[pace] # 页面加载期间顶部的进度条 # 有关详细信息：https://github.com/CodeByZach/pace
    enable = true
    color = "blue" # 所有可用颜色：# ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
    theme = "minimal" # 所有可用主题：# ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple","corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
    
[watermark] # 水印配置
    enable = true
    # 水印内容（允许 HTML 格式）
    content = "皂荚"
    # 水印透明度
    opacity = 0.1
    # 水印父节点
    appendTo = ".wrapper>main"
    # 单水印宽度 单位：px
    width = 150
    # 单水印高度 单位：px
    height = 20
    # 水印行间距 单位：px
    rowSpacing = 60
    # 水印列间距 单位：px
    colSpacing = 30
    # 水印旋转角度 单位：deg
    rotate = 15
    # 水印字体大小，单位：rem
    fontSize = 0.85
    # FixIt 0.2.13 | 新增 水印字体
    fontFamily = "inherit"
    
# FixIt 0.2.8 | 新增 兼容性设置
[compatibility] # 兼容性配置
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

  # FixIt 0.2.14 | 新增 在左上角或者右上角显示 GitHub 开源链接
[githubCorner] # 在左上角或者右上角显示 GitHub 开源链接
    enable = false
    permalink = "https://github.com/crack-dawn/CTGU-Hugo-Blog.io"
    title = "在 GitHub 上查看源代码"
    position = "left" # ["left", "right"]
[author]
    name = "crack-dawn"
    email = ""
    link = "https://github.com/crack-dawn/"
    avatar = "" # FixIt 0.2.18 | 新增
# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Header config # 站牌标题
[header]
  # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
  desktopMode = "sticky"
  # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
  mobileMode = "auto"
# FixIt 0.2.0 | NEW Header title config
  [header.title]
    logo = "./my/hugo.svg" # URL of the LOGO
    name = "A common CTGUer's blog" # title name

# 主页信息设置
[home]
  rss = 10 # RSS 文章数目
  [home.profile]# 主页个人信息
    enable = true
    gravatarEmail = "" # Gravatar 邮箱，用于优先在主页显示的头像
    avatarURL = "./my/hugo.svg" # 主页显示头像的 URL
    title = "显而不易见" # 主页显示的网站标题 (支持 HTML 格式)
    subtitle = "追求星辰大海,还是沉湎虚拟现实?" # 主页显示的网站副标题
    typeit = true # 是否为副标题显示打字机动画
    social = false # 是否显示社交账号
    disclaimer = "" # 免责声明 (支持 HTML 格式)
  [home.posts]# 主页文章列表
    enable = true
    paginate = 10 # 主页每页显示文章数量
# 作者的社交信息设置
  [social]
    GitHub = ""
    Bilibili = ""
    QQ = ""
    QQGroup = "" 
    Discord = ""
    Email = ""
    RSS = true


# 更改文章页面配置
[page]
      # FixIt 0.2.18 | 新增 是否启用文章作者头像
    authorAvatar = true
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FixIt 0.2.18-lts.5 | 新增 是否在 RSS 中隐藏一篇文章
    hiddenFromRss = false
    # FixIt 0.3.0 | 新增 是否在相关文章中隐藏一篇文章
    hiddenFromRelated = false
    # 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    # FixIt 0.2.18 | 更改 如果设为 "force"，文章中的图片将强制按照画廊形式呈现
    lightgallery = false
    # 是否使用 ruby 扩展语法
    ruby = true
    # 是否使用 fraction 扩展语法
    fraction = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = true
    # FixIt 0.3.0 | 新增 是否显示查看文章源码的链接
    linkToSource = true

    # # FixIt 0.3.0 | 新增 是否显示编辑文章的链接
    # linkToEdit = false
    # # FixIt 0.3.0 | 新增 是否显示报告文章问题的链接
    # linkToReport = false

    # 是否在 RSS 中显示全文内容
    rssFullText = false
    # FixIt 0.2.13 | 新增 页面样式 ["narrow", "normal", "wide", ...]
    pageStyle = "normal"
    # FixIt 0.2.17 | 更改 开启自动书签支持
    # 如果为 true，则在关闭页面时保存阅读进度
    autoBookmark = false
    # FixIt 0.2.17 | 新增 是否使用 字数统计
    wordCount = true
    # FixIt 0.2.17 | 新增 是否使用 预计阅读
    readingTime = true
    # FixIt 0.2.17 | 新增 文章结束标志
    endFlag = ""
    # FixIt 0.2.18 | 新增 是否开启即时页面
    instantPage = false
    # FixIt 0.3.0 | 新增 是否在侧边栏显示集合列表
    collectionList = true
    # FixIt 0.3.0 | 新增 是否在文章末尾显示集合导航
    collectionNavigation = true

# FixIt 0.2.15 | 新增 转载配置
    [page.repost]
      enable = false
      url = ""
    # 目录配置
    [page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      keepStatic = true
      # 是否使侧边目录自动折叠展开
      auto = true
      # FixIt 0.2.13 | 新增 目录位置 ["left", "right"]
      position = "right"
    # FixIt 0.2.13 | 新增 在文章开头显示提示信息，提醒读者文章内容可能过时
    [page.expirationReminder]
      enable = false
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = false
    # FixIt 0.3.0 | 新增 页面标题配置
    [page.heading]
      # FixIt 0.3.6 | 新增 是否自动大写标题
      capitalize = false
      # 配合 `markup.tableOfContents.ordered` 参数使用
      [page.heading.number]
        # 是否启用自动标题编号
        enable = true
        [page.heading.number.format]
          h1 = "{title}"
          h2 = "{h2}.{title}"
          h3 = "{h2}.{h3}.{title}"
          h4 = "{h2}.{h3}.{h4}.{title}"
          h5 = "{h2}.{h3}.{h4}.{h5}.{title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6}.{title}"
    # 代码配置
    [page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # FixIt 0.2.13 | 新增 是否显示代码块的编辑按钮
      edit = true
      # 默认展开显示的代码行数
      maxShownLines = 15
    # KaTeX 数学公式 (https://katex.org)
    [page.math]
      enable = true
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # FixIt 0.3.0 | 新增 [试验性功能] 缓存图床图片到本地，详见：https://github.com/hugo-fixit/FixIt/pull/362
    [page.cacheRemoteImages]
      enable = false
      # 用本地图片链接替换远程图片链接 (放置在 public/images/remote/)
      replace = false
    # FixIt 0.3.0 | 新增 相关内容配置 (https://gohugo.io/content-management/related/)
    [page.related]
      enable = false
      count = 5
    # FixIt 0.2.17 | 新增 赞赏设置
    [page.reward]
      enable = false
      animation = false
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "after"
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | 新增 二维码图片展示模式，可选值：["static", "fixed"]，默认：`static`
      mode = "static"
    [page.reward.ways]
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
    # 文章页面的分享信息设置
    [page.share]
      enable = true
      Twitter = true
      Facebook = true
      Weibo = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Linkedin = false
      Myspace = true
      Blogger = true
      Baidu = true
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

 