
 # [params]

[backToTop]
    enable = true
    scrollpercent = true

[readingProgress] # 全局页面 阅读进度条配置
    enable = true
    start = "left"      # 可用值：["left", "right"]
    position = "bottom"    # 可用值：["top", "bottom"]
    reversed = true
    light = ""
    dark = ""
    height = "2px"
[pace] # 页面加载期间顶部的进度条 # 有关详细信息：https://github.com/CodeByZach/pace
    enable = true
    # 所有可用颜色：
    # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
    color = "blue"
    # 所有可用主题：
    # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
    # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
    theme = "minimal"
 
# Header config # 站牌标题
[header]
  # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
  desktopMode = "sticky"
  # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
  mobileMode = "auto"
# FixIt 0.2.0 | NEW Header title config
  [header.title]
    logo = "./my/hugo.svg" # URL of the LOGO
    name = "A common CTGUer's blog" # title name

# 中文主页信息设置
[home]
  # RSS 文章数目
  rss = 10
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "./my/hugo.svg"
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "显而不易见"
    # 主页显示的网站副标题
    subtitle = "追求星辰大海,还是沉湎虚拟现实?"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = false
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 10
    
#  # 作者的社交信息设置
#  [social]
#     GitHub = "SHUGUG"
#     Bilibili = "260088"
#     QQ = "https://jq.qq.com/?_wv=1027&k=602U8xAj"
#     QQGroup = "https://jq.qq.com/?_wv=1027&k=602U8xAj" 
#     Discord = ""
#     Email = "shuosc@duck.com"
#     RSS = true

    
# 更改文章页面配置
[page]
# 代码配置
    [page.code]  
        # 是否显示代码块的复制按钮
        copy = true
        # FixIt 0.2.13 | 新增 是否显示代码块的编辑按钮
        edit = true
        # 默认展开显示的代码行数
        maxShownLines = 15
     # FixIt 0.2.15 | 新增 转载配置
    [page.repost]
      enable = false
      url = ""
    # FixIt 0.2.0 | 新增 目录配置
    [page.toc]
      # 是否使用目录
      enable = true
      # FixIt 0.2.9 | 新增 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
      # FixIt 0.2.13 | 新增 目录位置 ["left", "right"]
      position = "right"

    # FixIt 0.2.14 | 新增 文章编辑
    [page.edit]
      enable = false
      # FixIt 0.2.15 | 更改 编辑的基础链接
      # url = "/edit/branch-name/subdirectory-name" # 相对于 `gitRepo`
      # url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # 完整链接
      url = "/content"
    # FixIt 0.2.0 | 更改 KaTeX 数学公式 (https://katex.org)
    [page.math]
      enable = true
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # FixIt 0.2.0 | 新增 Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # FixIt 0.2.0 | 更改 文章页面的分享信息设置
    [page.share]
      enable = true
      Weibo = true
      Baidu = true
      Twitter = false
      Facebook = false
      Linkedin = true
      
[watermark] # 水印配置
    enable = true
    # 水印内容（允许 HTML 格式）
    content = "皂荚"
    # 水印透明度
    opacity = 0.1
    # 水印父节点
    appendTo = ".wrapper>main"
    # 单水印宽度 单位：px
    width = 150
    # 单水印高度 单位：px
    height = 20
    # 水印行间距 单位：px
    rowSpacing = 60
    # 水印列间距 单位：px
    colSpacing = 30
    # 水印旋转角度 单位：deg
    rotate = 15
    # 水印字体大小，单位：rem
    fontSize = 0.85
    # FixIt 0.2.13 | 新增 水印字体
    fontFamily = "inherit"
    
# FixIt 0.2.8 | 新增 兼容性设置
[compatibility] # 兼容性配置
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

  # FixIt 0.2.14 | 新增 在左上角或者右上角显示 GitHub 开源链接
[githubCorner] # 在左上角或者右上角显示 GitHub 开源链接
    enable = false
    permalink = "https://github.com/crack-dawn/CTGU-Hugo-Blog.io"
    title = "在 GitHub 上查看源代码"
    position = "left" # ["left", "right"]
  
    
[author]
    name = "crack-dawn"
    email = ""
    link = "https://github.com/crack-dawn/CTGU-Hugo-Blog.io"
    avatar = "" # FixIt 0.2.18 | 新增

# # 网站地图配置
# [sitemap]
#   changefreq = "weekly"
#   filename = "sitemap.xml"
#   priority = 0.5

 
   
    
