baseURL = 'https://crack-dawn.github.io/CTGU-Hugo-Blog.io/'
languageCode = 'en-us'
title = "A CTGUer's New Hugo Site"
theme = ["hugo-embed-pdf-shortcode", "FixIt"]
enableInlineShortcodes = true

[params]
  [params.archives]
    paginate = 20
    dateFormat = "01-02"


